---

- name: Download telegraf package
  get_url: url="https://dl.influxdata.com/telegraf/releases/telegraf-1.0.1.x86_64.rpm" dest="/tmp/telegraf.rpm"
  when: ansible_os_family == "RedHat"

- name: Download telegraf
  get_url: url="https://dl.influxdata.com/telegraf/releases/telegraf_1.0.1_amd64.deb" dest="/tmp/telegraf.deb"
  when: ansible_os_family == "Debian"

- name: Install telegraf
  yum: name="/tmp/telegraf.rpm" state="present"
  when: ansible_os_family == "RedHat"

- name: Install telegraf
  apt: deb="/tmp/telegraf.deb" state="present"
  when: ansible_os_family == "Debian"

- name: Copy telegraf conf file
  copy: src="telegraf.conf" dest="/etc/telegraf/telegraf.conf"

- name: Enable start up and restart telegraf
  service: name="telegraf" enabled="yes" state="started"
