---

- name: Make sure log dir exists
  file: path="{{supervisor_child_log_dir}}" state="directory"
  become: no

- name: Copy supervisor template
  template: src="supervisord.conf.template.j2" dest="{{project_home}}/supervisord.conf.template"
  become: no

- name: Make sure socket file exists for supervisor
  copy: dest="/tmp/supervisor.sock" mode="0755" content=""
  become: no

- name: Install supervisor
  pip: name="supervisor" state="present"

- name: Start supervisord
  shell: chdir="{{project_home}}" supervisord
  ignore_errors: yes
  register: supervisord
  become: no
  changed_when: supervisord.stderr and supervisord.stderr.find("Error") == -1
