---
- name: Add erlang repo
  command: rpm --import http://packages.erlang-solutions.com/rpm/erlang_solutions.asc
  register: rpmimport
  changed_when: rpmimport.stdout != ""

- name: Install erlang repo
  copy: src="erlang-solutions.repo" dest="/etc/yum.repos.d/erlang-solutions.repo"  

- name: Install erlang
  yum: state="present" name="erlang" disablerepo=epel

- name: Get rabbitmq package
  get_url: url="https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server-3.6.0-1.noarch.rpm" dest="/tmp/rabbitmq.rpm" 

- name: Download and install rabbitmq package
  yum: state=present name="/tmp/rabbitmq.rpm"

- name: Start and make rabbitmq service available on start up
  service: name="rabbitmq-server" enabled=yes state=started