---

- name: Install erlang
  yum: state="present" name="erlang"
  when: ansible_os_family == "RedHat"

- name: Install erlang
  apt: state="present" name="erlang"
  when: ansible_os_family == "Debian"

- name: Get rabbitmq package
  get_url: url="https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server-3.6.0-1.noarch.rpm" dest="/tmp/rabbitmq.rpm"
  when: ansible_os_family == "RedHat"

- name: Get rabbitmq package
  get_url: url="https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server_3.6.0-1_all.deb" dest="/tmp/rabbitmq.deb"
  when: ansible_os_family == "Debian"

- name: Install rabbitmq package
  yum: state=present name="/tmp/rabbitmq.rpm"
  when: ansible_os_family == "RedHat"

- name: Install rabbitmq package
  apt: state=present deb="/tmp/rabbitmq.deb"
  when: ansible_os_family == "Debian"

- name: Start and make rabbitmq service available on start up
  service: name="rabbitmq-server" enabled=yes state=started
