---

- name: Install erlang repo
  copy: src="erlang-solutions.repo" dest="/etc/yum.repos.d/erlang-solutions.repo"  

- name: Add epel for dependencies
  copy: src='epel-{{ansible_distribution_major_version}}.repo.j2' dest="/etc/yum.repos.d/epel.repo"

- name: Install erlang
  yum: state="present" name="erlang" disablerepo="epel"

- name: Get rabbitmq package
  get_url: url="https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server-3.6.0-1.noarch.rpm" dest="/tmp/rabbitmq.rpm" 

- name: Install rabbitmq package
  yum: state=present name="/tmp/rabbitmq.rpm"

- name: Start and make rabbitmq service available on start up
  service: name="rabbitmq-server" enabled=yes state=started