---
- name: Add epel for dependencies
  yum_repository:
      name: epel
      description: EPEL yum repo
      baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install erlang
  yum: state="present" name="erlang"

- name: Get rabbitmq package
  get_url: url="https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server-3.6.0-1.noarch.rpm" dest="/tmp/rabbitmq.rpm"

- name: Install rabbitmq package
  yum: state=present name="/tmp/rabbitmq.rpm"

- name: Start and make rabbitmq service available on start up
  service: name="rabbitmq-server" enabled=yes state=started
